// נקודות עניין בפילדלפיה — כל הזמנים/מרחקים חושבו מ-City Hall (מרכז העיר) ברגל/בתחב"צ (SEPTA).
// מחירי כניסה הם הערכה בדולרים למבוגר, נכונים למועד הכתיבה — כדאי לבדוק באתר הרשמי לפני הביקור.
const CITY_HALL = { lat: 39.9526, lng: -75.1652 };

const CATEGORIES = {
  history: { label: "היסטוריה", icon: "🏛️", color: "#8a5a2b" },
  museums: { label: "מוזיאונים", icon: "🖼️", color: "#5b4b8a" },
  parks: { label: "פארקים וטבע", icon: "🌳", color: "#2f8f5b" },
  food: { label: "אוכל ושווקים", icon: "🥨", color: "#c0392b" },
  family: { label: "משפחה וילדים", icon: "🎡", color: "#d68910" },
  shopping: { label: "קניות ובידור", icon: "🛍️", color: "#1f6f8b" },
  daytrip: { label: "טיולי יום", icon: "🚗", color: "#7a7a2f" },
};

const PLACES = [
  {
    id: "independence-hall",
    name: "אינדפנדנס הול",
    category: "history",
    lat: 39.9489,
    lng: -75.15,
    address: "520 Chestnut St",
    cost: 0,
    costLabel: "חינם (נדרש כרטיס כניסה מראש)",
    duration: "45 דקות",
    walk: 12,
    transit: 6,
    desc: "המקום בו נחתמה הכרזת העצמאות האמריקאית וגובשה החוקה. סיור מודרך קצר וחובה לכל מי שמתעניין בהיסטוריה האמריקאית.",
    tip: "כרטיסים חינמיים אבל מוגבלים במספר — כדאי להזמין מראש באתר ה-NPS או להגיע מוקדם לעמדת החלוקה.",
  },
  {
    id: "liberty-bell",
    name: "פעמון החירות (Liberty Bell)",
    category: "history",
    lat: 39.9496,
    lng: -75.1503,
    address: "526 Market St",
    cost: 0,
    costLabel: "חינם",
    duration: "20 דקות",
    walk: 12,
    transit: 6,
    desc: "הפעמון הסדוק המפורסם שהפך לסמל החירות האמריקאית. נמצא ממש ליד אינדפנדנס הול, אפשר לשלב באותו ביקור.",
    tip: "אין צורך בכרטיס — תור בדרך כלל זורם מהר בבוקר.",
  },
  {
    id: "constitution-center",
    name: "מרכז החוקה הלאומי",
    category: "history",
    lat: 39.9526,
    lng: -75.1502,
    address: "525 Arch St",
    cost: 18,
    costLabel: "$18",
    duration: "שעה וחצי",
    walk: 14,
    transit: 6,
    desc: "מוזיאון אינטראקטיבי על החוקה האמריקאית וההיסטוריה הפוליטית של ארה״ב, מתאים גם למי שלא בקיא בנושא.",
    tip: "ההצגה הרב-תקשורתית במרכז האולם היא השיא — אל תפספסו אותה.",
  },
  {
    id: "betsy-ross",
    name: "בית בטסי רוס",
    category: "history",
    lat: 39.953,
    lng: -75.1454,
    address: "239 Arch St",
    cost: 7,
    costLabel: "$7",
    duration: "30 דקות",
    walk: 16,
    transit: 7,
    desc: "ביתה של האישה שלפי המסורת תפרה את דגל ארה״ב הראשון. בית עץ קטן ומקסים מהמאה ה-18.",
    tip: "אפשר לדלג אם הזמן קצר — הכי מומלץ למי שממש אוהב היסטוריה קולוניאלית.",
  },
  {
    id: "elfreths-alley",
    name: "אלפרת'ס אלי",
    category: "history",
    lat: 39.9539,
    lng: -75.1444,
    address: "Elfreth's Alley",
    cost: 0,
    costLabel: "חינם (רחוב פתוח)",
    duration: "15 דקות",
    walk: 17,
    transit: 8,
    desc: "הרחוב המיושב הוותיק ביותר באמריקה — שורת בתי לבנים קולוניאליים מצולמת במיוחד.",
    tip: "רחוב מגורים אמיתי — תיירים מתבקשים לשמור על שקט ולא להיכנס לחצרות.",
  },
  {
    id: "christ-church",
    name: "כריסט צ'רץ' ובית הקברות",
    category: "history",
    lat: 39.9518,
    lng: -75.1447,
    address: "20 N American St",
    cost: 5,
    costLabel: "$3-5",
    duration: "30 דקות",
    walk: 15,
    transit: 7,
    desc: "הכנסייה שבה התפללו וושינגטון ופרנקלין, ובית הקברות הסמוך שבו קבור בנג'מין פרנקלין עצמו.",
    tip: "מסורת מקומית: משליכים מטבע על קברו של פרנקלין לשם מזל.",
  },
  {
    id: "art-museum",
    name: "מוזיאון האמנות של פילדלפיה",
    category: "museums",
    lat: 39.9656,
    lng: -75.181,
    address: "2600 Benjamin Franklin Pkwy",
    cost: 30,
    costLabel: "$30 (תרומה חופשית בכל יום ראשון ראשון בחודש)",
    duration: "2-3 שעות",
    walk: 55,
    transit: 15,
    desc: "אחד מהמוזיאונים הגדולים בארה״ב, עם אוסף ענק מרנואר ועד סזאן. הבניין עצמו איקוני בזכות סצנת הריצה מ'רוקי'.",
    tip: "קו האוטובוס Phlash התיירותי או קו 38 עוצרים ממש מול הכניסה.",
  },
  {
    id: "rocky-steps",
    name: "מדרגות רוקי",
    category: "museums",
    lat: 39.9657,
    lng: -75.1811,
    address: "מול מוזיאון האמנות",
    cost: 0,
    costLabel: "חינם",
    duration: "15 דקות",
    walk: 55,
    transit: 15,
    desc: "המדרגות המפורסמות מהסרט 'רוקי' — כולם עוצרים לתמונה עם הידיים באוויר, ולצידן פסל רוקי עצמו.",
    tip: "בואו מוקדם בבוקר כדי לתפוס תמונה בלי עשרות תיירים נוספים בפריים.",
  },
  {
    id: "barnes",
    name: "קרן בארנס (Barnes Foundation)",
    category: "museums",
    lat: 39.9585,
    lng: -75.1739,
    address: "2025 Benjamin Franklin Pkwy",
    cost: 30,
    costLabel: "$30",
    duration: "שעתיים",
    walk: 40,
    transit: 10,
    desc: "אוסף אימפרסיוניזם ופוסט-אימפרסיוניזם יוצא דופן (רנואר, סזאן, מאטיס) שנאסף על ידי אספן אקסצנטרי אחד.",
    tip: "כדאי להזמין כרטיסים מראש — הכניסה מוגבלת במספר מבקרים.",
  },
  {
    id: "franklin-institute",
    name: "מכון פרנקלין",
    category: "museums",
    lat: 39.9581,
    lng: -75.173,
    address: "222 N 20th St",
    cost: 27,
    costLabel: "$27",
    duration: "3 שעות",
    walk: 42,
    transit: 10,
    desc: "מוזיאון מדע ענק ואינטראקטיבי — לב אנושי ענק שאפשר לעבור דרכו, IMAX, ותערוכות חלל וטכנולוגיה.",
    tip: "מומלץ מאוד למשפחות עם ילדים — כדאי לתכנן חצי יום.",
  },
  {
    id: "natural-sciences",
    name: "האקדמיה למדעי הטבע",
    category: "museums",
    lat: 39.9578,
    lng: -75.1728,
    address: "1900 Benjamin Franklin Pkwy",
    cost: 24,
    costLabel: "$24",
    duration: "שעה וחצי",
    walk: 40,
    transit: 10,
    desc: "מוזיאון היסטוריה של הטבע עם שלדי דינוזאורים, אקווריום קטן ותערוכות על עולם החי.",
    tip: "טוב לשלב באותו יום עם מכון פרנקלין הסמוך.",
  },
  {
    id: "please-touch",
    name: "מוזיאון פליז טאץ' (לילדים קטנים)",
    category: "family",
    lat: 39.9814,
    lng: -75.2119,
    address: "Memorial Hall, Fairmount Park",
    cost: 21,
    costLabel: "$21",
    duration: "שעתיים",
    walk: 90,
    transit: 25,
    desc: "מוזיאון אינטראקטיבי המיועד לילדים עד גיל 7 — תפאורות משחק, קרוסלה עתיקה ופעילויות חושיות.",
    tip: "מומלץ להגיע ברכב או במונית — קצת רחוק מהמרכז.",
  },
  {
    id: "penn-museum",
    name: "מוזיאון פן (ארכיאולוגיה)",
    category: "museums",
    lat: 39.9489,
    lng: -75.1912,
    address: "3260 South St",
    cost: 18,
    costLabel: "$18",
    duration: "שעה וחצי",
    walk: 55,
    transit: 15,
    desc: "מוזיאון הארכיאולוגיה והאנתרופולוגיה של אוניברסיטת פנסילבניה — אוסף מצרי מרשים וגולגולת ספינקס אמיתית.",
    tip: "נמצא בקמפוס Penn — כדאי לשלב עם טיול קצר בקמפוס האוניברסיטה.",
  },
  {
    id: "eastern-state",
    name: "בית הסוהר Eastern State Penitentiary",
    category: "history",
    lat: 39.9679,
    lng: -75.1727,
    address: "2027 Fairmount Ave",
    cost: 27,
    costLabel: "$27",
    duration: "שעה וחצי",
    walk: 45,
    transit: 12,
    desc: "כלא היסטורי נטוש ומרשים עם אדריכלות גותית, שם ריצה אל קפונה מאסר. אודיו-גייד מעולה כלול במחיר.",
    tip: "באוקטובר הופך ל'Terror Behind the Walls' — אטרקציית אימה פופולרית (ומחיר גבוה יותר).",
  },
  {
    id: "magic-gardens",
    name: "הגנים הקסומים של פילדלפיה",
    category: "museums",
    lat: 39.9398,
    lng: -75.1573,
    address: "1020 South St",
    cost: 12,
    costLabel: "$12",
    duration: "45 דקות",
    walk: 25,
    transit: 10,
    desc: "מיצב אמנות רחוב מרהיב מפסיפס זכוכית ומראות שנבנה על ידי אמן מקומי לאורך עשרות שנים.",
    tip: "אחרי הביקור כדאי להמשיך לטייל ברחוב סאות' הסמוך.",
  },
  {
    id: "rittenhouse",
    name: "כיכר ריטנהאוס",
    category: "parks",
    lat: 39.9491,
    lng: -75.172,
    address: "Rittenhouse Square",
    cost: 0,
    costLabel: "חינם",
    duration: "לפי הצורך",
    walk: 20,
    transit: 8,
    desc: "הכיכר האלגנטית ביותר בעיר, מוקפת בתי קפה ומסעדות שוות — מקום נעים לפיקניק או מנוחה בין אטרקציות.",
    tip: "מלא בשוק אוכרים ואירועים בסופי שבוע בקיץ — כדאי לבדוק לוח אירועים.",
  },
  {
    id: "wissahickon",
    name: "עמק וויסהיקון (פארק פיירמאונט)",
    category: "parks",
    lat: 40.027,
    lng: -75.216,
    address: "Valley Green Rd",
    cost: 0,
    costLabel: "חינם",
    duration: "חצי יום",
    walk: 999,
    transit: 35,
    desc: "אחד מהפארקים העירוניים הגדולים בארה״ב — שבילי הליכה ורכיבה על אופניים לאורך נחל טבעי, הרחק מרעש העיר.",
    tip: "הכי נוח להגיע ברכב או מונית; יש חניה ליד Valley Green Inn.",
  },
  {
    id: "spruce-harbor",
    name: "Spruce Street Harbor Park (עונתי, קיץ)",
    category: "parks",
    lat: 39.9459,
    lng: -75.1408,
    address: "301 S Christopher Columbus Blvd",
    cost: 0,
    costLabel: "חינם (עלות לאוכל/פעילויות)",
    duration: "שעה",
    walk: 15,
    transit: 8,
    desc: "פארק קיצי צף על הנהר עם ערסלים, אורות צבעוניים ודוכני אוכל — אווירה כיפית וקליטה במיוחד בערב.",
    tip: "פתוח רק בעונת הקיץ (מאי-ספטמבר בערך) — בדקו תאריכים לפני שמתכננים.",
  },
  {
    id: "reading-terminal",
    name: "שוק Reading Terminal Market",
    category: "food",
    lat: 39.9532,
    lng: -75.1594,
    address: "51 N 12th St",
    cost: 0,
    costLabel: "כניסה חינם, מנה $8-15",
    duration: "שעה-שעתיים",
    walk: 10,
    transit: 5,
    desc: "שוק אוכל היסטורי ותוסס עם עשרות דוכנים — מקום מצוין לטעום צ'יזסטייק, אמיש בייקינג ומטבחים מכל העולם.",
    tip: "פתוח כל יום חוץ מכמה חנויות שסגורות בשבת (בעלות אמיש).",
  },
  {
    id: "italian-market",
    name: "השוק האיטלקי (9th Street)",
    category: "food",
    lat: 39.9339,
    lng: -75.1594,
    address: "9th St, בין Christian ל-Wharton",
    cost: 0,
    costLabel: "חינם, קניות לפי טעם",
    duration: "שעה",
    walk: 45,
    transit: 12,
    desc: "השוק האיטלקי החוצות הוותיק ביותר בארה״ב — גבינות, סלמי, ירקות טריים ומאפיות איטלקיות אותנטיות.",
    tip: "הכי חי בבוקר של יום שבת.",
  },
  {
    id: "south-street",
    name: "רחוב סאות' (South Street)",
    category: "shopping",
    lat: 39.9424,
    lng: -75.1567,
    address: "South St",
    cost: 0,
    costLabel: "חינם, קניות/אוכל לפי טעם",
    duration: "שעה-שעתיים",
    walk: 20,
    transit: 9,
    desc: "רחוב תוסס עם חנויות בוטיק, גלריות, מסעדות וחיי לילה — אווירה אלטרנטיבית וצבעונית.",
    tip: "בערבי סוף שבוע הרחוב הומה — טוב למי שמחפש בילוי ערב.",
  },
  {
    id: "philly-zoo",
    name: "גן החיות של פילדלפיה",
    category: "family",
    lat: 39.9736,
    lng: -75.1925,
    address: "3400 W Girard Ave",
    cost: 26,
    costLabel: "$26",
    duration: "3 שעות",
    walk: 60,
    transit: 20,
    desc: "גן החיות הראשון בארה״ב (1874), עם מאות מיני בעלי חיים ומסלול הליכה ייחודי בגובה העצים (Zoo360).",
    tip: "כדאי לקנות כרטיסים אונליין מראש — לפעמים זול יותר ונחסך תור.",
  },
  {
    id: "city-hall",
    name: "מגדל התצפית של City Hall",
    category: "history",
    lat: 39.9526,
    lng: -75.1652,
    address: "1401 JFK Blvd",
    cost: 8,
    costLabel: "$8",
    duration: "30 דקות",
    walk: 5,
    transit: 2,
    desc: "עלייה למגדל בניין העירייה המרשים (הבניין העירוני הגבוה בעולם עם שעון בעת בנייתו) לתצפית 360 מעלות על העיר.",
    tip: "מספר המבקרים לעלייה מוגבל בכל שעה — כדאי לקנות כרטיס לשעה מוקדמת ביום.",
  },
  {
    id: "love-park",
    name: "לאב פארק (LOVE Park)",
    category: "parks",
    lat: 39.9535,
    lng: -75.1673,
    address: "JFK Plaza",
    cost: 0,
    costLabel: "חינם",
    duration: "10 דקות",
    walk: 5,
    transit: 2,
    desc: "הפסל האייקוני LOVE של רוברט אינדיאנה — צילום חובה ממש ליד עיריית העיר.",
    tip: "ממוקם בדיוק בדרך בין ה-City Hall לפארקווי, קל לשלב תוך כדי הליכה.",
  },
  {
    id: "longwood-gardens",
    name: "Longwood Gardens (טיול יום)",
    category: "daytrip",
    lat: 39.8711,
    lng: -75.6693,
    address: "Kennett Square, PA (כ-50 ק״מ מהעיר)",
    cost: 25,
    costLabel: "$25-30",
    duration: "חצי יום",
    walk: 999,
    transit: 999,
    desc: "אחד מגני הנוי המרהיבים בארה״ב — חממות ענק, מזרקות מוזיקליות ופרחים עונתיים. נדרש רכב, אין תחבורה ציבורית נוחה.",
    tip: "כ-45 דקות נסיעה ברכב מהעיר; שכירת רכב או Uber/Lyft הם האופציות המעשיות היחידות.",
  },
];
